-- ============================================================================
-- PrintDesk — SQLite schema (v1)
--
-- Runs embedded in the browser via sqlite-wasm, stored in OPFS. Single user,
-- single connection, so there is no auth, no tenancy column, and no row-level
-- security: nothing here is reachable over a network.
--
-- TYPE CONVENTIONS
--   ids         TEXT, a UUID generated by crypto.randomUUID()
--   money       REAL, in MXN pesos
--   booleans    INTEGER, 0 or 1
--   timestamps  TEXT, ISO 8601 UTC (e.g. '2026-09-24T14:05:00.000Z')
--   dates       TEXT, 'YYYY-MM-DD'
--
-- WHY REAL FOR MONEY, NOT INTEGER CENTAVOS
--   All pricing arithmetic happens in src/pricing.ts. SQLite REAL is an IEEE
--   754 double, which is exactly what a JavaScript number is, so a peso value
--   round-trips through storage bit-for-bit. Storing centavos would force a
--   rounding step on every read and write and could make the stored total
--   disagree with what pricing.ts computed. The float hazard is in repeated
--   arithmetic, not in storage, and the arithmetic lives in one tested module.
--   Final invoice figures are explicitly rounded to 2 decimals before being
--   frozen onto a quote.
--
-- FOREIGN KEYS ARE OFF BY DEFAULT IN SQLITE.
--   Every connection must issue `PRAGMA foreign_keys = ON`, or the ON DELETE
--   CASCADE clauses below silently do nothing. See src/db/schema.ts.
-- ============================================================================


-- Tracks which migration level the file is at, so a database created by an
-- older version of the app can be upgraded rather than discarded.
create table if not exists schema_version (
  version    integer not null primary key,
  applied_at text    not null
);


-- ---------------------------------------------------------------------------
-- SETTINGS — one row, enforced by a fixed primary key.
-- Holds the defaults that were previously retyped into every job.
-- ---------------------------------------------------------------------------
create table if not exists settings (
  id                      integer primary key default 1,

  business_name           text,
  rfc                     text,
  currency                text    not null default 'MXN',

  electricity_rate        real    not null default 2.8,    -- MXN per kWh
  default_markup_percent  real    not null default 30.0,
  default_iva_enabled     integer not null default 0,
  iva_rate                real    not null default 0.16,   -- 16%; 8% border zone
  failure_rate_percent    real    not null default 0.0,
  minimum_order           real    not null default 0.0,    -- MXN floor on a job's total price
  quote_validity_days     integer not null default 15,

  created_at              text    not null,
  updated_at              text    not null,

  -- Guarantees this table can never hold more than one row.
  constraint settings_singleton check (id = 1),
  constraint settings_iva_rate_sane check (iva_rate >= 0 and iva_rate <= 1),
  constraint settings_failure_sane  check (failure_rate_percent >= 0 and failure_rate_percent < 100),
  constraint settings_iva_bool      check (default_iva_enabled in (0, 1))
);


-- ---------------------------------------------------------------------------
-- CUSTOMERS — replaces the free-text client string, which made "RC Hobbies"
-- and "RC hobbies" two separate customers and made repeat history impossible.
-- ---------------------------------------------------------------------------
create table if not exists customers (
  id           text    not null primary key,
  name         text    not null,
  contact_name text,
  email        text,
  phone        text,
  rfc          text,
  notes        text,
  is_active    integer not null default 1,
  created_at   text    not null,
  updated_at   text    not null,

  constraint customers_name_not_blank check (length(trim(name)) > 0),
  constraint customers_active_bool    check (is_active in (0, 1))
);

-- Case-insensitive uniqueness: stops the same customer being entered twice
-- with different capitalisation, which a plain UNIQUE would allow.
create unique index if not exists customers_name_unique
  on customers (lower(trim(name)));

create index if not exists customers_active_idx on customers (is_active);


-- ---------------------------------------------------------------------------
-- PRINTERS — machine cost is one of the two largest real costs the app
-- currently ignores entirely. A $25,000 MXN printer over 3,000 productive
-- hours is about $8.33/h before maintenance, and none of it is recovered.
-- ---------------------------------------------------------------------------
create table if not exists printers (
  id                        text    not null primary key,
  name                      text    not null,
  model                     text,
  power_watts               real    not null default 200.0,
  purchase_cost             real    not null default 0.0,   -- MXN
  amortization_hours        integer not null default 3000,
  maintenance_cost_per_hour real    not null default 0.0,   -- nozzles, belts, plates
  build_volume              text,
  status                    text    not null default 'active',
  created_at                text    not null,
  updated_at                text    not null,

  constraint printers_status_valid  check (status in ('active', 'maintenance', 'retired')),
  constraint printers_amort_sane    check (amortization_hours > 0),
  constraint printers_power_sane    check (power_watts >= 0)
);

create unique index if not exists printers_name_unique on printers (lower(trim(name)));


-- ---------------------------------------------------------------------------
-- FILAMENTS — the catalog: what a material costs today. Distinct from physical
-- stock, which lives in filament_spools. The original app conflated the two and
-- called the result "inventory" while tracking no quantity at all.
-- ---------------------------------------------------------------------------
create table if not exists filaments (
  id                 text    not null primary key,
  brand              text    not null,
  type               text    not null,                 -- PLA, PETG, ABS, ASA...
  color              text    not null,
  hex                text,
  price_per_kg       real    not null,                 -- MXN, current price
  -- Whether price_per_kg is the figure the supplier charged including IVA. If
  -- that IVA is creditable, true material cost is the pre-IVA amount, and
  -- costing with the gross figure overstates cost on every job.
  price_includes_iva integer not null default 1,
  density_g_cm3      real,
  supplier           text,
  is_active          integer not null default 1,
  created_at         text    not null,
  updated_at         text    not null,

  constraint filaments_price_positive check (price_per_kg >= 0),
  constraint filaments_iva_bool       check (price_includes_iva in (0, 1)),
  constraint filaments_active_bool    check (is_active in (0, 1)),
  constraint filaments_hex_format     check (
    hex is null or (length(hex) = 7 and substr(hex, 1, 1) = '#')
  )
);

create index if not exists filaments_active_idx on filaments (is_active);


-- ---------------------------------------------------------------------------
-- FILAMENT SPOOLS — physical stock: which spools exist, how much is left.
-- ---------------------------------------------------------------------------
create table if not exists filament_spools (
  id              text    not null primary key,
  filament_id     text    not null references filaments(id) on delete restrict,
  label           text,
  lot_code        text,
  initial_grams   real    not null default 1000.0,
  grams_remaining real    not null default 1000.0,
  purchase_cost   real,                                  -- MXN actually paid
  purchased_at    text,                                  -- YYYY-MM-DD
  opened_at       text,
  is_depleted     integer not null default 0,
  created_at      text    not null,
  updated_at      text    not null,

  constraint spools_remaining_sane check (grams_remaining >= 0 and grams_remaining <= initial_grams),
  constraint spools_depleted_bool  check (is_depleted in (0, 1))
);

create index if not exists spools_filament_idx on filament_spools (filament_id);
create index if not exists spools_available_idx on filament_spools (is_depleted);


-- ---------------------------------------------------------------------------
-- QUOTES — the customer-facing artifact. Separating quote status from
-- production status is what makes a win rate measurable: the original app
-- jumped straight to 'queued', conflating "we priced it" with "we're printing".
-- ---------------------------------------------------------------------------
create table if not exists quotes (
  id               text    not null primary key,
  customer_id      text    references customers(id) on delete set null,

  folio            integer not null unique,              -- human-facing number
  status           text    not null default 'draft',
  title            text,
  notes            text,
  currency         text    not null default 'MXN',

  -- IVA is optional per quote, and the RATE is snapshotted beside the flag so
  -- a future rate change (or an 8% border-zone job) cannot rewrite history.
  iva_enabled      integer not null default 0,
  iva_rate         real    not null default 0.16,

  markup_percent   real    not null default 30.0,
  -- Snapshotted from settings at creation, for the same reason: changing the
  -- company electricity rate must not silently re-price an issued quote.
  electricity_rate real    not null default 2.8,

  valid_until      text,                                 -- YYYY-MM-DD
  sent_at          text,
  decided_at       text,

  -- Frozen output of src/pricing.ts, written when the quote leaves draft and
  -- rounded to 2 decimals. Null while still a draft, where totals are
  -- recomputed live from the inputs.
  total_pre_tax    real,
  total_iva        real,
  total            real,
  frozen_at        text,

  created_at       text    not null,
  updated_at       text    not null,

  constraint quotes_status_valid check (
    status in ('draft', 'sent', 'accepted', 'rejected', 'expired', 'cancelled')
  ),
  constraint quotes_iva_bool      check (iva_enabled in (0, 1)),
  constraint quotes_iva_rate_sane check (iva_rate >= 0 and iva_rate <= 1),
  constraint quotes_folio_positive check (folio > 0),
  -- A quote past draft must carry frozen totals; a draft must not.
  constraint quotes_frozen_when_issued check (
    (status = 'draft' and frozen_at is null)
    or (status <> 'draft' and frozen_at is not null and total is not null)
  )
);

create index if not exists quotes_status_idx   on quotes (status);
create index if not exists quotes_customer_idx on quotes (customer_id);


-- ---------------------------------------------------------------------------
-- JOBS
-- ---------------------------------------------------------------------------
create table if not exists jobs (
  id               text    not null primary key,
  quote_id         text    not null references quotes(id) on delete cascade,
  printer_id       text    references printers(id) on delete set null,

  name             text    not null,
  quantity         integer not null default 1,
  print_time_hours real    not null default 0,
  -- Snapshotted from the printer so retiring or reassigning a machine does not
  -- change what an already-quoted job cost to run.
  power_watts      real    not null default 200.0,
  machine_rate     real    not null default 0.0,           -- MXN/hour, snapshotted from the printer

  packaging_cost   real    not null default 0.0,          -- MXN per unit
  finishing_cost   real    not null default 0.0,          -- MXN per unit

  status           text    not null default 'queued',
  queue_position   integer,
  due_date         text,                                  -- replaces "picks up Thursday" in notes
  priority         text    not null default 'normal',
  notes            text,

  started_at       text,
  completed_at     text,
  created_at       text    not null,
  updated_at       text    not null,

  constraint jobs_quantity_positive check (quantity >= 1),
  constraint jobs_status_valid   check (status in ('queued', 'printing', 'done', 'cancelled', 'failed')),
  constraint jobs_priority_valid check (priority in ('low', 'normal', 'high', 'rush'))
);

create index if not exists jobs_status_idx on jobs (status);
create index if not exists jobs_quote_idx  on jobs (quote_id);
create index if not exists jobs_queue_idx  on jobs (queue_position);
create index if not exists jobs_due_idx    on jobs (due_date);


-- ---------------------------------------------------------------------------
-- JOB MATERIALS — consumption per job, with the price FROZEN at quote time.
-- The original app already copied pricePerKg rather than joining live; that
-- behaviour was correct and is preserved deliberately.
-- ---------------------------------------------------------------------------
create table if not exists job_materials (
  id             text    not null primary key,
  job_id         text    not null references jobs(id) on delete cascade,
  filament_id    text    references filaments(id) on delete set null,
  spool_id       text    references filament_spools(id) on delete set null,

  -- Denormalised so deleting a catalog entry cannot erase what a historical
  -- job was actually printed in.
  material_label text    not null default '',
  color_label    text    not null default '',

  grams          real    not null default 0,
  price_per_kg   real    not null,                        -- MXN, snapshotted
  sort_order     integer not null default 0,
  created_at     text    not null,

  constraint job_materials_grams_positive check (grams >= 0),
  constraint job_materials_price_positive check (price_per_kg >= 0)
);

create index if not exists job_materials_job_idx on job_materials (job_id);


-- ---------------------------------------------------------------------------
-- JOB LABOR STAGES — the per_job/per_unit split is the fix for setup labor
-- being multiplied by quantity. A 0.25 h slicing stage on a 50-unit batch was
-- charged 50 times, which loses every batch bid.
-- ---------------------------------------------------------------------------
create table if not exists job_labor_stages (
  id         text    not null primary key,
  job_id     text    not null references jobs(id) on delete cascade,
  name       text    not null default '',
  hours      real    not null default 0,
  rate       real    not null default 0,                  -- MXN per hour
  scope      text    not null default 'per_unit',
  sort_order integer not null default 0,
  created_at text    not null,

  constraint labor_scope_valid    check (scope in ('per_job', 'per_unit')),
  constraint labor_hours_positive check (hours >= 0),
  constraint labor_rate_positive  check (rate >= 0)
);

create index if not exists job_labor_job_idx on job_labor_stages (job_id);


-- ---------------------------------------------------------------------------
-- JOB ACTUALS — what happened, versus what was quoted. Without this the app
-- never learns which job types are consistently underpriced.
-- ---------------------------------------------------------------------------
create table if not exists job_actuals (
  job_id             text    not null primary key references jobs(id) on delete cascade,
  actual_print_hours real,
  actual_grams       real,
  actual_labor_hours real,
  failed_attempts    integer not null default 0,
  wasted_grams       real    not null default 0,
  notes              text,
  recorded_at        text    not null,
  updated_at         text    not null,

  constraint actuals_failed_sane check (failed_attempts >= 0),
  constraint actuals_waste_sane  check (wasted_grams >= 0)
);


-- ---------------------------------------------------------------------------
-- Convenience view: current queue with its customer, for the Queue screen.
-- Money is NOT totalled here — src/pricing.ts owns all cost arithmetic and a
-- second implementation in SQL would inevitably drift from it.
-- ---------------------------------------------------------------------------
create view if not exists v_job_overview as
select
  j.id            as job_id,
  j.name          as job_name,
  j.status        as job_status,
  j.quantity,
  j.due_date,
  j.priority,
  j.queue_position,
  j.created_at,
  q.id            as quote_id,
  q.folio,
  q.status        as quote_status,
  q.iva_enabled,
  q.iva_rate,
  q.markup_percent,
  coalesce(c.name, '') as customer_name,
  p.name          as printer_name
from jobs j
join quotes q          on q.id = j.quote_id
left join customers c  on c.id = q.customer_id
left join printers p   on p.id = j.printer_id;
